/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/mannequin.glb -t -s 
Author: Jacob.Elhatmi (https://sketchfab.com/Jacob.Elhatmi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wig-mannequin-63b3a3b35e9242d2b914064af26bf7fe
Title: Wig Mannequin
*/

import * as THREE from "three";

import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube001_Material002_0: THREE.Mesh;
  };
  materials: {
    ["Material.002"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "./../models/mannequin.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001_Material002_0.geometry}
        material={materials["Material.002"]}
        position={[0, -2, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.5}
      />
    </group>
  );
}

useGLTF.preload("./../models/mannequin.glb");
